# Называния афйла, отображается в разделе Workflow

name: PHP_Comoser

on:
  push:
    branches: main

jobs:

  name_of_job:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: First_step
       run : echo ok
     - name : List
       run : ls -la
