# Называния афйла, отображается в разделе Workflow

name: PHP_Comoser

env:  
  APP : "name"
  ID_COMMIT : ${{ github.sha }}

# Acton сработывает только когда пушит в ветку маин
on:
  push:
    branches: main

jobs:

  name_of_job:
  
    runs-on: ubuntu-latest
    
    env:
      VAR1 : "Key 1"
    steps:
     - uses: actions/checkout@v1
     
     - name: Git version
       run : git version
       
     - name: App name
       run : echo ${{ env.APP}}
       
     - name: List
       run : ls -la
       
     - name: Local environment
       run : echo ${{ ENV.VAR1}}
       
  name_of_second_job:
  
    runs-on: ubuntu-latest
    
    needs: [name_of_job]
    
    steps:
    
     - name: First_step
       run : echo ok
       
     - name: List
       run : ls -la
