# Называния афйла, отображается в разделе Workflow

name: PHP_Comoser

# Acton сработывает только когда пушит в ветку маин
on:
  push:
    branches: main

jobs:

  name_of_job:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: Git version
       run : git version
     - name: First_step
       run : echo ok
     - name: List
       run : ls -la
  name_of_second_job:
    runs-on: ubuntu-latest
    needs: [name_of_job]
    steps:
     - name: First_step
       run : echo ok
     - name: List
       run : ls -la
